version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/helloworld

hooks:
  AfterInstall:
    - location: scripts/start_flask.sh
      runas: root
      timeout: 20
  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 20
      runas: root
